### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ptlab-la** [unionco/craft-sync-db#17]
Getting the following output...

`[2021-02-23T20:16:54.159483-08:00] sync.NOTICE: Starting database sync [] []
[2021-02-23T20:16:54.165338-08:00] sync.INFO: Beginning remote dump [] []
[2021-02-23T20:16:55.744867-08:00] sync.INFO: Beginning remote download [] []
[2021-02-23T20:16:55.812963-08:00] sync.ERROR: return non-zero: 1 [] []`

**Comment by abryrath** [comment]
@ptlab-la Can you please share:
1. craft-sync-db version
2. syncdb version
3. PHP version
4. Craft version

**Comment by abryrath** [comment]
@ptlab-la Based on the image you sent via email, this appears to be a configuration issue. The first failure comes from the SCP step due to the db_dump.sql.tar.gz file not existing at the specified path. I would check the paths on your staging server configuration and see where the db_dump is actually being created.

**Comment by ptlab-la** [comment]
@abryrath thank you.

I'm trying to run this on my local to sync with the staging server. One thing to note: the database is hosted on Amazon RDS and not directly on the staging server. Does the plugin work still work this?

I don't believe it's even doing the db dump as it shows the log immediately and no file is created at the location.

Here is the info:

1. craft-sync-db version = 0.8.0.1
2. syncdb version = 0.8.0
3. PHP version = 7.4.2
4. Craft version = Craft Pro 3.6.2

**Comment by abryrath** [comment]
@ptlab-la I have used the plugin with AWS/RDS before, so that shouldn't be a problem. You do need to connect directly to a linux server with mysqldump installed and the server must be able to connect to the DB using your `.env` credentials. If you can connect to the database from your Craft installation, the plugin should be able to connect to it as well.

**Comment by extensibleseth** [comment]
I see the same error. 

```
% php craft sync-db/sync linuxweb normal

    Craft can’t connect to the database. Check your connection settings.

Unknown command: sync-db/sync
Caused by: Exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "sync-db/sync".'

in /vendor/yiisoft/yii2/base/Module.php:543

Stack trace:
#0 /vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('sync-db/sync', Array)
#1 /vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('sync-db/sync', Array)
#2 /vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('sync-db/sync', Array)
#3 /vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#4 /craft(23): yii\base\Application->run()
#5 {main}
```
